spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-eu-west-3.pooler.supabase.com:6543/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.xjjkfbiqsysydlguobxd}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:O0dUNQNJha99dMLa}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.port=${PORT:8080}
